"""Generate the encrypted Cython configuration module for a secure fastsite release."""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from pathlib import Path

import yaml
from cryptography.hazmat.primitives.ciphers.aead import AESGCM


ROOT = Path(__file__).resolve().parent
DEFAULT_CONFIG = ROOT / "build-config.yml"
TARGET = ROOT / "src" / "fastsite" / "_compiled_config.pyx"
KEY_BYTES = 32
NONCE_BYTES = 12


def _load_config(path: Path) -> dict[str, object]:
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as error:
        raise ValueError(f"cannot read build config: {path}") from error
    if not isinstance(raw, dict) or not isinstance(raw.get("databases"), dict) or not raw["databases"]:
        raise ValueError("build config must contain at least one databases entry")
    for name, database in raw["databases"].items():
        if not isinstance(name, str) or not isinstance(database, dict):
            raise ValueError("database entries must be named mappings")
        required = {"db_type", "host", "port", "database", "user", "password"}
        missing = sorted(key for key in required if not database.get(key))
        if missing:
            raise ValueError(f"database {name} is missing: {', '.join(missing)}")
        if database["db_type"] not in {"mysql", "doris"}:
            raise ValueError(f"database {name} has unsupported db_type")
    return raw


def _split_and_mask(payload: bytes) -> tuple[list[tuple[bytes, bytes]], list[int]]:
    shard_count = min(7, max(3, len(payload) // 48))
    split_points = sorted(random.sample(range(1, len(payload)), shard_count - 1))
    chunks: list[bytes] = []
    start = 0
    for end in [*split_points, len(payload)]:
        chunks.append(payload[start:end])
        start = end
    masked = []
    for chunk in chunks:
        mask = os.urandom(len(chunk))
        masked.append((bytes(left ^ right for left, right in zip(chunk, mask)), mask))
    order = list(range(len(masked)))
    random.shuffle(order)
    return [masked[index] for index in order], order


def _bytes_literal(value: bytes) -> str:
    return repr(value)


def _render_module(parts: list[tuple[bytes, bytes]], order: list[int]) -> str:
    rows = ",\n".join(f"    ({_bytes_literal(data)}, {_bytes_literal(mask)})" for data, mask in parts)
    return f'''# cython: language_level=3
# Generated by build_embedded_config.py. Do not commit this file.
import json
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_PARTS = (\n{rows},\n)
_ORDER = {tuple(order)!r}


def _restore():
    restored = [b"" for _ in _ORDER]
    for current_index, original_index in enumerate(_ORDER):
        data, mask = _PARTS[current_index]
        restored[original_index] = bytes(left ^ right for left, right in zip(data, mask))
    return b"".join(restored)


def get_database_configurations():
    payload = _restore()
    key = payload[:{KEY_BYTES}]
    encrypted = payload[{KEY_BYTES}:]
    nonce = encrypted[:{NONCE_BYTES}]
    plaintext = AESGCM(key).decrypt(nonce, encrypted[{NONCE_BYTES}:], None)
    return json.loads(plaintext.decode("utf-8"))["databases"]
'''


def build(config_path: Path, output_path: Path) -> None:
    config = _load_config(config_path)
    plaintext = json.dumps(config, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    key = AESGCM.generate_key(bit_length=256)
    nonce = os.urandom(NONCE_BYTES)
    encrypted = nonce + AESGCM(key).encrypt(nonce, plaintext, None)
    module = _render_module(*_split_and_mask(key + encrypted))
    for database in config["databases"].values():
        for secret in (str(database["user"]), str(database["password"])):
            if secret in module:
                raise RuntimeError("refusing to write generated module containing a plaintext credential")
    output_path.write_text(module, encoding="utf-8")
    print(f"generated {output_path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=TARGET)
    args = parser.parse_args()
    try:
        build(args.config.resolve(), args.output.resolve())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
